### ISSUE TITLE
数据库可否开放由开发者自行创建新表而不只是使用kv存储

### ISSUE THREAD

**Issue by Adsicmes** [opq-osc/mahiro#4]
如题

**Comment by fz6m** [comment]
mahiro 里绝大部分的方法和对象都是开放访问的，`mahiro.db` 是一个 [knex](https://github.com/knex/knex) 对象，你可以调用上面的方法自行创建、检查自己的表，然后修改数据，这些都可以在插件中自行封装完成，使用方法参考 [`packages/mahiro/src/database/index.ts`](https://github.com/opq-osc/mahiro/blob/main/packages/mahiro/src/database/index.ts) 里已有的逻辑和 knex 官方文档即可。

**Comment by fz6m** [comment]
`mahiro.db.db` 已在 `v15.0.2` 最新版本中公开。

`mahiro.db.db` 是一个 [knex](https://github.com/knex/knex) 对象，你可以调用上面的方法自行创建、检查自己的表，然后修改数据，这些都可以在插件中自行封装完成，使用方法参考 [`packages/mahiro/src/database/index.ts`](https://github.com/opq-osc/mahiro/blob/main/packages/mahiro/src/database/index.ts) 里已有的逻辑和 knex 官方文档即可。
